language: android
dist: trusty
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
env:
  global:
    secure: coy85NnAimMMEVAqTGU6mY6nCI1ruEb0PXZKVlvsA4kE2Ears+S2kO4p5LgJ2eGAPz3PPeBIX7pB+YEpaJTcQEtTC8JbBowEHc6GnO6WoPAAef0D1DKgcNl1JXKO9ptbVFXWBSdPP3iS+LaVZI7SvpVwcHkJrOAWWUrWqUmDhYGW9A9etnZag+Rem8JPN5bhemtdkb08l2XnE2eiSk6LIeO4qZur5fYH/J/mFyznIWINGU+GJaNMgrznUGuBRhozmSpK3Gd+XKLVS4iJeEfdsQBR0tk/XOiHEDbUKtrMoLBiXJSiQx0pUegeGBLAd1YnY3meygbbKLJB9a9ZpJR3jgXo0Lc/RJgOWftbbqtLejcuXDi082zjzsBEdTwzMFG3eRbGzqQecP7s43FMU3k06o0LjcJvG6aEQD7MqoD/wB+ZICLAAyjjZJe1gCoLZTFmX5f2Nb7+uVttld2YCVCFCnlv2ZiOX5DQyNVh4bR1LFS5Q9YZdZBJ07aDfBOPiFv0ETzvlMgerp7enPctN7bzOcORTRI0DpVQLMszL83Za6p5RFWmIMd/ZSlxDPa6T/LnuYzYqD61nMbZ05cDt6S8p90QO2uDJCe2DhhQomVU4lvPGrJ1gahgAneAe/Nve4yaQJYdmHnogSKShTQ4kucPA0f/nBzOcIjCdE1Xx38GRDs=
addons:
  sonarcloud:
    organization: slt-programmers
    token:
      secure: coy85NnAimMMEVAqTGU6mY6nCI1ruEb0PXZKVlvsA4kE2Ears+S2kO4p5LgJ2eGAPz3PPeBIX7pB+YEpaJTcQEtTC8JbBowEHc6GnO6WoPAAef0D1DKgcNl1JXKO9ptbVFXWBSdPP3iS+LaVZI7SvpVwcHkJrOAWWUrWqUmDhYGW9A9etnZag+Rem8JPN5bhemtdkb08l2XnE2eiSk6LIeO4qZur5fYH/J/mFyznIWINGU+GJaNMgrznUGuBRhozmSpK3Gd+XKLVS4iJeEfdsQBR0tk/XOiHEDbUKtrMoLBiXJSiQx0pUegeGBLAd1YnY3meygbbKLJB9a9ZpJR3jgXo0Lc/RJgOWftbbqtLejcuXDi082zjzsBEdTwzMFG3eRbGzqQecP7s43FMU3k06o0LjcJvG6aEQD7MqoD/wB+ZICLAAyjjZJe1gCoLZTFmX5f2Nb7+uVttld2YCVCFCnlv2ZiOX5DQyNVh4bR1LFS5Q9YZdZBJ07aDfBOPiFv0ETzvlMgerp7enPctN7bzOcORTRI0DpVQLMszL83Za6p5RFWmIMd/ZSlxDPa6T/LnuYzYqD61nMbZ05cDt6S8p90QO2uDJCe2DhhQomVU4lvPGrJ1gahgAneAe/Nve4yaQJYdmHnogSKShTQ4kucPA0f/nBzOcIjCdE1Xx38GRDs=
script:
- "./gradlew sonarqube"
notifications:
  slack: homeworkcarmenarjan:YreL13iWQ3xpqtXLpudbTy2m
before_install:
- openssl aes-256-cbc -K $encrypted_b2d0e6c8f8ad_key -iv $encrypted_b2d0e6c8f8ad_iv
  -in macrolog-service-account-key.json.enc -out macrolog-service-account-key.json
  -d
deploy: 
  provider: gae
  keyfile: macrolog-service-account-key.json
  project: api-4969776351416209484-853923
  on: 
    branch: release